version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/node
permissions:
  - object: /home/ec2-user
    owner: deployer
    group: deployment
    type:
      - directory
      - file
hooks:
  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: deployer
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 600
      runas: deployer
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
      runas: deployer
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 120
      runas: deployer
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: deployer