#!/bin/sh

ssh ec2-user@ec2-3-16-109-16.us-east-2.compute.amazonaws.com <<EOF
    echo 'i am here'
    cd ~/deployment-project
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF
